<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishSingleFile>true</PublishSingleFile>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Benchmark\**" />
    <EmbeddedResource Remove="Benchmark\**" />
    <None Remove="Benchmark\**" />
  </ItemGroup>

</Project>